version: '2'
services:
  webapp:
    image: samarth/samarth-webapp:v0.1.0
    build:
      context: ./
      dockerfile: Dockerfile
    network_mode: host
    restart: always
    expose:
      - 8080
    ports:
    - "8080:8080"
