version: '2'
services:
  webapp:
    image: samarth/samarth-webapp:v0.1.0
    build:
      context: ./
      dockerfile: Dockerfile
    network_mode: host
    restart: always
    expose:
      - 8080
    ports:
      - "80:8080"
  samarth:
    image: samarth/samarth-platform:v0.1.0
    build:
      context: ./
      dockerfile: 
    network_mode: host
    restart: always
    expose:
      -8081
    ports:
      - "80:8081"